# Install and run the application
name: Continuous Integration
on: [push, pull_request]
jobs:
  ci:
    name: continuous integration
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-version: ['8.0', '8.1', '8.2', '8.3']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Fix autocrlf on Windows
        if: matrix.operating-system == 'windows-latest'
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--prefer-dist --optimize-autoloader"
      - name: Create .php-cs-fixer.php
        if: matrix.operating-system != 'windows-latest'
        run: echo "<?php \$config = new phootwork\fixer\Config();\$config->getFinder()->in(__DIR__.'/src');return \$config;" > .php-cs-fixer.php
      - name: Create .php-cs-fixer.php on Windows
        if: matrix.operating-system == 'windows-latest'
        run: |
          New-Item .php-cs-fixer.php
          Set-Content .php-cs-fixer.php '<?php $config = new phootwork\fixer\Config();$config->getFinder()->in(__DIR__."/src");return $config;'
      - name: Test the configuration
        run: vendor/bin/php-cs-fixer fix -v --diff --dry-run
